modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
[[mods]]
modId="buildersmod"
version="${file.jarVersion}"
displayName="Builders Mod"
logoFile="buildersmod.png"
credits="Builders mod by Edamame"
description='''
Mod by Edamame.
'''

[[dependencies.tutorialmod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
